name: Build & Release (Zenodo-ready)

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-docs.txt

      - name: Generate zenodo.json from CITATION.cff
        run: |
          python tools/cff_to_zenodo.py CITATION.cff zenodo.json
          echo "Generated zenodo.json:"
          cat zenodo.json

      - name: Build Sphinx docs to docs/_site
        run: |
          sphinx-build -b html docs docs/_site -W --keep-going

      - name: Create docs archive
        run: |
          cd docs/_site
          zip -r ../../docs-html.zip .
          cd ../../
          echo "::notice title=Artifacts::Prepared zenodo.json and docs-html.zip"

      - name: Read version from CITATION.cff
        id: getver
        run: |
          VER=$(grep '^version:' CITATION.cff | awk '{print $2}')
          echo "version=$VER" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.getver.outputs.version }}
          name: "STAMPLATE JSONSchema v${{ steps.getver.outputs.version }}"
          body: |
            Automated release for v${{ steps.getver.outputs.version }}.

            Artifacts:
            - docs-html.zip (Sphinx HTML docs)
            - zenodo.json (DataCite metadata for Zenodo)

            After Zenodo mints the DOI, add it to CITATION.cff and README.
          draft: false
          prerelease: false
          files: |
            docs-html.zip
            zenodo.json

